services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: non-sola
      POSTGRES_PASSWORD: example
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
